### ISSUE TITLE
InvalidProgramException when returning task with nullable struct

### ISSUE THREAD

**Issue by andriivitiv** [Singulink/RuntimeNullables#4]
```
Unhandled exception. System.InvalidProgramException: Common Language Runtime detected an invalid program.
   at FodyTest.Program.DoSomethingAsync()
   at FodyTest.Program.Main(String[] args) in /home/andrii/development/FodyTest/FodyTest/Program.cs:line 9
   at FodyTest.Program.<Main>(String[] args)
```

```cs
using System.Threading.Tasks;

namespace FodyTest
{
    class Program
    {
        static Task Main(string[] args)
        {
            return DoSomethingAsync();
        }

        // Works fine with reference types (e.g. string)
        // But throws the exception with value types (e.g. bool)
        static Task<bool?> DoSomethingAsync()
        {
            return Task.FromResult((bool?) null);
        }
    }
}
```

**Comment by mikernet** [comment]
This is the same underlying issue as the previous issue filed, will be fixed shortly! :)

**Comment by mikernet** [comment]
P.S. If you want a quick fix you can annotate the method with `[return: NullChecks(false)]` but I will have a new version posted very shortly.

**Comment by mikernet** [comment]
Fixed via https://github.com/Singulink/RuntimeNullables/commit/4bd7513b5b111033278c94b3f2a01026ddd683db
